### ISSUE TITLE
seems interesting

### ISSUE THREAD

**Issue by shouko** [NTUOSC/mercurius-panel#1]
what's this for? seems interesting OwO

**Comment by m80126colin** [comment]
Front-end original from Mercurius: https://github.com/NTUOSC/mercurius-union/tree/master/dist

I want to rewrite it with Vue.

**Comment by rschiang** [comment]
Wouldn't vanilla JS be sufficient enough? Serving Vue on card reader might
break due to unstable outbound network connection. o____o)"

**Comment by squirrel532** [comment]
Rewriting in Vue won't change the protocol between front-end(On tablet)  and back-end (card reader).

**Comment by rschiang** [comment]
I mean "if Vue (or any external library) is used, you'd have to make sure
that they are served locally."

Referencing Vue through CDN would possibly break if the outbound network
connection were not stable. So this is more than an advice.

Squirrel <notifications@github.com> 於 2017年5月12日 週五 19:30 寫道：
